package com.flightsearch.app.utils;

import java.util.HashMap;
import java.util.Map;

public class IataMapper {

    private static final Map<String, String> CITY_MAP = new HashMap<>();

    static {
        put("moscow", "SVO");
        put("москва", "SVO");
        put("sheremetyevo", "SVO");
        put("шереметьево", "SVO");
        put("domodedovo", "DME");
        put("домодедово", "DME");
        put("vnukovo", "VKO");
        put("внуково", "VKO");
        put("saint petersburg", "LED");
        put("st petersburg", "LED");
        put("санкт-петербург", "LED");
        put("питер", "LED");
        put("spb", "LED");
        put("ekaterinburg", "SVX");
        put("екатеринбург", "SVX");
        put("novosibirsk", "OVB");
        put("новосибирск", "OVB");
        put("sochi", "AER");
        put("сочи", "AER");
        put("kazan", "KZN");
        put("казань", "KZN");
        put("krasnodar", "KRR");
        put("краснодар", "KRR");
        put("vladivostok", "VVO");
        put("владивосток", "VVO");
        put("irkutsk", "IKT");
        put("иркутск", "IKT");
        put("ufa", "UFA");
        put("уфа", "UFA");
        put("samara", "KUF");
        put("самара", "KUF");
        put("rostov", "ROV");
        put("ростов", "ROV");
        put("omsk", "OMS");
        put("омск", "OMS");
        put("chelyabinsk", "CEK");
        put("челябинск", "CEK");
        put("perm", "PEE");
        put("пермь", "PEE");
        put("nizhny novgorod", "GOJ");
        put("нижний новгород", "GOJ");
        put("volgograd", "VOG");
        put("волгоград", "VOG");
        put("murmansk", "MMK");
        put("мурманск", "MMK");
        put("kaliningrad", "KGD");
        put("калининград", "KGD");
        put("astrakhan", "ASF");
        put("астрахань", "ASF");
        put("tyumen", "TJM");
        put("тюмень", "TJM");
        put("surgut", "SGC");
        put("сургут", "SGC");
        put("khabarovsk", "KHV");
        put("хабаровск", "KHV");
        put("yakutsk", "YKS");
        put("якутск", "YKS");
        put("magadan", "GDX");
        put("магадан", "GDX");
        put("norilsk", "NSK");
        put("норильск", "NSK");

        put("minsk", "MSQ");
        put("минск", "MSQ");
        put("kyiv", "KBP");
        put("kiev", "KBP");
        put("киев", "KBP");
        put("almaty", "ALA");
        put("алматы", "ALA");
        put("nur-sultan", "NQZ");
        put("astana", "NQZ");
        put("астана", "NQZ");
        put("tashkent", "TAS");
        put("ташкент", "TAS");
        put("baku", "GYD");
        put("баку", "GYD");
        put("tbilisi", "TBS");
        put("тбилиси", "TBS");
        put("yerevan", "EVN");
        put("ереван", "EVN");
        put("bishkek", "FRU");
        put("бишкек", "FRU");
        put("dushanbe", "DYU");
        put("душанбе", "DYU");
        put("ashgabat", "ASB");
        put("ашхабад", "ASB");

        put("paris", "CDG");
        put("париж", "CDG");
        put("london", "LHR");
        put("лондон", "LHR");
        put("berlin", "BER");
        put("берлин", "BER");
        put("frankfurt", "FRA");
        put("франкфурт", "FRA");
        put("amsterdam", "AMS");
        put("амстердам", "AMS");
        put("madrid", "MAD");
        put("мадрид", "MAD");
        put("barcelona", "BCN");
        put("барселона", "BCN");
        put("rome", "FCO");
        put("рим", "FCO");
        put("milan", "MXP");
        put("милан", "MXP");
        put("vienna", "VIE");
        put("вена", "VIE");
        put("zurich", "ZRH");
        put("цюрих", "ZRH");
        put("geneva", "GVA");
        put("женева", "GVA");
        put("brussels", "BRU");
        put("брюссель", "BRU");
        put("prague", "PRG");
        put("прага", "PRG");
        put("warsaw", "WAW");
        put("варшава", "WAW");
        put("budapest", "BUD");
        put("будапешт", "BUD");
        put("bucharest", "OTP");
        put("бухарест", "OTP");
        put("sofia", "SOF");
        put("софия", "SOF");
        put("athens", "ATH");
        put("афины", "ATH");
        put("lisbon", "LIS");
        put("лиссабон", "LIS");
        put("copenhagen", "CPH");
        put("копенгаген", "CPH");
        put("stockholm", "ARN");
        put("стокгольм", "ARN");
        put("oslo", "OSL");
        put("осло", "OSL");
        put("helsinki", "HEL");
        put("хельсинки", "HEL");
        put("riga", "RIX");
        put("рига", "RIX");
        put("tallinn", "TLL");
        put("таллин", "TLL");
        put("vilnius", "VNO");
        put("вильнюс", "VNO");
        put("istanbul", "IST");
        put("стамбул", "IST");
        put("ankara", "ESB");
        put("анкара", "ESB");
        put("antalya", "AYT");
        put("анталья", "AYT");

        put("dubai", "DXB");
        put("дубай", "DXB");
        put("abu dhabi", "AUH");
        put("абу-даби", "AUH");
        put("doha", "DOH");
        put("доха", "DOH");
        put("riyadh", "RUH");
        put("эр-рияд", "RUH");
        put("tehran", "IKA");
        put("тегеран", "IKA");
        put("tel aviv", "TLV");
        put("тель-авив", "TLV");
        put("beijing", "PEK");
        put("пекин", "PEK");
        put("shanghai", "PVG");
        put("шанхай", "PVG");
        put("tokyo", "NRT");
        put("токио", "NRT");
        put("osaka", "KIX");
        put("осака", "KIX");
        put("seoul", "ICN");
        put("сеул", "ICN");
        put("bangkok", "BKK");
        put("бангкок", "BKK");
        put("singapore", "SIN");
        put("сингапур", "SIN");
        put("hong kong", "HKG");
        put("гонконг", "HKG");
        put("delhi", "DEL");
        put("дели", "DEL");
        put("mumbai", "BOM");
        put("мумбай", "BOM");
        put("colombo", "CMB");
        put("коломбо", "CMB");

        put("new york", "JFK");
        put("нью-йорк", "JFK");
        put("los angeles", "LAX");
        put("лос-анджелес", "LAX");
        put("miami", "MIA");
        put("майами", "MIA");
        put("chicago", "ORD");
        put("чикаго", "ORD");
        put("san francisco", "SFO");
        put("сан-франциско", "SFO");
        put("toronto", "YYZ");
        put("торонто", "YYZ");
        put("montreal", "YUL");
        put("монреаль", "YUL");
        put("vancouver", "YVR");
        put("ванкувер", "YVR");
        put("cancun", "CUN");
        put("канкун", "CUN");
        put("mexico city", "MEX");
        put("мехико", "MEX");
        put("sao paulo", "GRU");
        put("сан-паулу", "GRU");
        put("buenos aires", "EZE");
        put("буэнос-айрес", "EZE");

        put("cairo", "CAI");
        put("каир", "CAI");
        put("casablanca", "CMN");
        put("касабланка", "CMN");
        put("johannesburg", "JNB");
        put("йоханнесбург", "JNB");
        put("sydney", "SYD");
        put("сидней", "SYD");
        put("melbourne", "MEL");
        put("мельбурн", "MEL");
    }

    private static void put(String city, String code) {
        CITY_MAP.put(city.toLowerCase(), code);
    }

    public static String getCode(String city) {
        if (city == null || city.trim().isEmpty()) return "XXX";
        String normalized = city.trim().toLowerCase();
        String code = CITY_MAP.get(normalized);
        if (code != null) return code;
        String upper = city.trim().toUpperCase();
        if (upper.length() >= 2 && upper.length() <= 3 && upper.matches("[A-Z]+")) {
            return upper.length() == 3 ? upper : upper + "X";
        }
        return upper.substring(0, Math.min(3, upper.length()));
    }
}
